Adds the heartbeat controller to the provider-local extension

diff --git a/hack/local-development/start-extension-provider-local b/hack/local-development/start-extension-provider-local
--- a/hack/local-development/start-extension-provider-local
+++ b/hack/local-development/start-extension-provider-local
@@ -35,6 +35,15 @@ export LEADER_ELECTION_NAMESPACE=garden
 export GO111MODULE=on
 export GARDENER_SHOOT_CLIENT=external
 
+# The namespace for the provider-local extension controller is required because it is where
+# gardenlet will look for the gardener-extension-heartbeat lease resource during shoot
+# health checks.
+heartbeat_namespace="$(kubectl get namespaces -l controllerregistration.core.gardener.cloud/name=provider-local -o jsonpath='{.items[0].metadata.name}')"
+if [ -z "$heartbeat_namespace" ]; then
+  echo "Could not find namespace for provider-local extension controller heart beats"
+  exit 1
+fi
+
 # sudo is required for now, as we need to manipulate /etc/hosts for making the shoot API server reachable on the host machine
 SUDO=
 if [ "$USER" != root ]; then
@@ -55,6 +64,7 @@ $SUDO go run \
   --service-host-ip="${SERVICE_HOST_IP}" \
   --metrics-bind-address="${METRICS_BIND_ADDRESS}" \
   --health-bind-address="${HEALTH_BIND_ADDRESS}" \
+  --heartbeat-namespace="${heartbeat_namespace}" \
   --gardener-version="$(cat "$(dirname $0)/../../VERSION")" \
   --backupbucket-local-dir="$ETCD_BACKUP_DIR" \
   --backupbucket-container-mount-path="$CONTAINER_PATH"
