refactor hack scripts for usage in extensions

diff --git a/hack/local-development/start-gardenlet b/hack/local-development/start-gardenlet
--- a/hack/local-development/start-gardenlet
+++ b/hack/local-development/start-gardenlet
@@ -14,21 +14,26 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.
 
-source $(dirname "${0}")/common
-source $(dirname "${0}")/local-imagevector-overwrite
+source $(dirname "${0}")/common/helpers
+source $(dirname "${0}")/common/local-imagevector-overwrite
 
 kubeconfig="$(mktemp_kubeconfig)"
+REPO_ROOT=$(dirname $0)/../..
 trap cleanup_kubeconfig EXIT
 
-imagevector_overwrite="$(mktemp_imagevector_overwrite)"
-trap cleanup_imagevector_overwrite EXIT
+file_imagevector_overwrite="$(mktemp_imagevector_overwrite github.com/gardener/gardener "$REPO_ROOT" "$REPO_ROOT"/charts)"
+if [ ! -f "$file_imagevector_overwrite" ]; then
+    echo "failed to generate local image vector override: $file_imagevector_overwrite"
+else
+  trap cleanup_imagevector_overwrite EXIT
 
-KUBECONFIG="${KUBECONFIG:-$kubeconfig}" \
-GARDEN_KUBECONFIG="${GARDEN_KUBECONFIG:-$kubeconfig}" \
-IMAGEVECTOR_OVERWRITE="$imagevector_overwrite" \
-GO111MODULE=on \
-    go run \
-      -mod=vendor \
-      -ldflags "$("$(dirname $0)"/../get-build-ld-flags.sh)" \
-      "$(dirname $0)"/../../cmd/gardenlet/main.go \
-      --config="$(dirname $0)"/../../dev/20-componentconfig-gardenlet.yaml
+  KUBECONFIG="${KUBECONFIG:-$kubeconfig}" \
+  GARDEN_KUBECONFIG="${GARDEN_KUBECONFIG:-$kubeconfig}" \
+  IMAGEVECTOR_OVERWRITE="$file_imagevector_overwrite" \
+  GO111MODULE=on \
+      go run \
+        -mod=vendor \
+        -ldflags "$("$(dirname $0)"/../get-build-ld-flags.sh)" \
+        "$(dirname $0)"/../../cmd/gardenlet/main.go \
+        --config="$(dirname $0)"/../../dev/20-componentconfig-gardenlet.yaml
+fi
