Add more component versions debug output

diff --git a/pkg/provider-local/node/Dockerfile b/pkg/provider-local/node/Dockerfile
--- a/pkg/provider-local/node/Dockerfile
+++ b/pkg/provider-local/node/Dockerfile
@@ -20,6 +20,10 @@ RUN systemctl enable run-userdata.service
 
 # TODO(marc1404): Remove once kindest/node uses runc >= v1.2.4
 # workaround issue with runc v1.2.3 provided by kindest/node:v1.32.0 by installing runc v1.2.4 manually (https://github.com/opencontainers/runc/pull/4555)
-COPY runc /usr/local/sbin/runc
+# COPY runc /usr/local/sbin/runc
+
+RUN runc --version || echo "Error while printing out runc version"
+RUN kind --version || echo "Error while printing out kind version"
+RUN containerd --version || echo "Error while printing out containerd version"
 
 ENTRYPOINT ["/usr/local/bin/entrypoint", "/sbin/init"]
